<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>EventSpine.Shared</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
